---
- name: Checking Mariadb containers
  include_role:
    role: service-check
  vars:
    service_check_services: "{{ mariadb_services }}"

- name: Waiting for MariaDB service to be ready through VIP
  command: "docker exec mariadb mysql -h {{ kolla_internal_fqdn }} -P {{ mariadb_port }} -u haproxy -e 'show databases;'"
  register: result
  until: result is success
  changed_when: False
  retries: 6
  delay: 10
