---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - "{{ mariadb_container_name }}"
  register: container_facts

- name: Checking free port for MariaDB
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ role_mariadb_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts[mariadb_container_name] is not defined

- name: Checking free port for MariaDB WSREP
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ mariadb_wsrep_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts[mariadb_container_name] is not defined

- name: Checking free port for MariaDB IST
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ mariadb_ist_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts[mariadb_container_name] is not defined

- name: Checking free port for MariaDB SST
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ mariadb_sst_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts[mariadb_container_name] is not defined
