---
- name: Creating haproxy mysql user
  become: true
  kolla_toolbox:
    module_name: mysql_user
    module_args:
      login_host: "{{ api_interface_address }}"
      login_port: "{{ role_mariadb_port }}"
      login_user: "{{ role_mariadb_database_user }}"
      login_password: "{{ role_mariadb_database_password }}"
      name: "haproxy"
      password: ""
      host: "%"
      priv: "*.*:USAGE"
  when: inventory_hostname == groups[role_mariadb_group][0]

- import_tasks: wait_for_loadbalancer.yml

- name: Creating the Percona XtraBackup database
  become: true
  kolla_toolbox:
    module_name: mysql_db
    module_args:
      login_host: "{{ role_mariadb_database_address }}"
      login_port: "{{ role_mariadb_database_port }}"
      login_user: "{{ role_mariadb_database_user }}"
      login_password: "{{ role_mariadb_database_password }}"
      name: "{{ mariadb_backup_database_schema }}"
  when:
    - enable_xtrabackup | bool
    - inventory_hostname == groups[role_mariadb_group][0]

- name: Creating database backup user and setting permissions
  become: true
  kolla_toolbox:
    module_name: mysql_user
    module_args:
      login_host: "{{ role_mariadb_database_address }}"
      login_port: "{{ role_mariadb_database_port }}"
      login_user: "{{ role_mariadb_database_user }}"
      login_password: "{{ role_mariadb_database_password }}"
      name: "{{ mariadb_backup_database_user }}"
      password: "{{ role_mariadb_database_backup_password }}"
      host: "%"
      priv: "*.*:CREATE TABLESPACE,RELOAD,PROCESS,SUPER,LOCK TABLES,REPLICATION CLIENT"
      append_privs: True
  when:
    - enable_xtrabackup | bool
    - inventory_hostname == groups[role_mariadb_group][0]

- name: Granting permissions on XtraBackup database to backup user
  become: true
  kolla_toolbox:
    module_name: mysql_user
    module_args:
      login_host: "{{ role_mariadb_database_address }}"
      login_port: "{{ role_mariadb_database_port }}"
      login_user: "{{ role_mariadb_database_user }}"
      login_password: "{{ role_mariadb_database_password }}"
      name: "{{ mariadb_backup_database_user }}"
      password: "{{ role_mariadb_database_backup_password }}"
      host: "%"
      priv: "{{ mariadb_backup_database_schema }}.*:CREATE,INSERT,SELECT"
      append_privs: True
  when:
    - enable_xtrabackup | bool
    - inventory_hostname == groups[role_mariadb_group][0]

- name: Cleaning up facts
  set_fact:
    delegate_host: "bootstraped"
