---
features:
  - Configure all openstack services to use the globally defined Certificate
    Authority to verify HTTPs connections. The global CA is configured by the
    'openstack_cacert' parameter.
