---
- import_tasks: register.yml

- include_tasks: config.yml

- include_tasks: clone.yml
  when:
    - glance_dev_mode | bool

- import_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers

- include_tasks: check.yml
