---
- include: register.yml
  when: inventory_hostname in groups['nova-api']

- include: config.yml

- include: config-nova-fake.yml
  when:
    - enable_nova_fake | bool
    - inventory_hostname in groups['compute']

- include: bootstrap.yml
  when: inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['compute']

- include: create_cells.yml

- name: Flush handlers
  meta: flush_handlers

- include: discover_computes.yml
