---
# This is necessary after new cells have been created to refresh the cell cache
# in nova scheduler.
- name: Refresh cell cache in nova scheduler
  become: true
  command: docker kill --signal HUP nova_scheduler
  changed_when: False
  when:
    - inventory_hostname in groups['nova-scheduler']
