---
# This play calls sighup on every service to refresh upgrade levels

# NOTE(mgoddard): Currently (just prior to Stein release), sending SIGHUP to
# nova compute services leaves them in a broken state in which they cannot
# start new instances. The following error is seen in the logs:
# "In shutdown, no new events can be scheduled"
# To work around this we restart the nova-compute services.
# Speaking to the nova team, this seems to be an issue in oslo.service,
# with a fix proposed here: https://review.openstack.org/#/c/641907.
# This issue also seems to affect the proxy services, which exit non-zero in
# reponse to a SIGHUP, so restart those too.
# The issue actually affects all nova services, since they remain with RPC
# version pinned to the previous release:
# https://bugs.launchpad.net/kolla-ansible/+bug/1833069.
# TODO(mgoddard): Remove this workaround when this bug has been fixed.

# - name: Send SIGHUP to nova services
#   become: true
#   command: docker exec -t {{ item.value.container_name }} kill -1 1
#   when:
#     - inventory_hostname in groups[item.value.group]
#     - item.value.enabled | bool
#     - item.key in nova_services_require_nova_conf
#   with_dict: "{{ nova_services }}"

- name: Restart nova services
  become: true
  kolla_docker:
    action: restart_container
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
    - item.key in nova_services_require_nova_conf
    - item.key != 'placement-api'
  with_dict: "{{ nova_services }}"
