---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ project_name }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ rabbitmq_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ project_name }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ rabbitmq_services }}"
  notify:
    - Restart rabbitmq container

- name: Copying over rabbitmq-env.conf
  become: true
  vars:
    service: "{{ rabbitmq_services['rabbitmq'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ project_name }}/rabbitmq-env.conf"
    mode: "0660"
  with_first_found:
    - "{{ node_custom_config }}/rabbitmq/{{ inventory_hostname }}/rabbitmq-env.conf"
    - "{{ node_custom_config }}/rabbitmq/rabbitmq-env.conf"
    - "rabbitmq-env.conf.j2"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart rabbitmq container

- name: Copying over rabbitmq.conf
  become: true
  vars:
    service: "{{ rabbitmq_services['rabbitmq'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ project_name }}/rabbitmq.conf"
    mode: "0660"
  with_first_found:
    - "{{ node_custom_config }}/rabbitmq/{{ inventory_hostname }}/rabbitmq.conf"
    - "{{ node_custom_config }}/rabbitmq/rabbitmq.conf"
    - "rabbitmq.conf.j2"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart rabbitmq container

- name: Copying over erl_inetrc
  become: true
  vars:
    service: "{{ rabbitmq_services['rabbitmq'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ project_name }}/erl_inetrc"
    mode: "0660"
  with_first_found:
    - "{{ node_custom_config }}/rabbitmq/{{ inventory_hostname }}/erl_inetrc"
    - "{{ node_custom_config }}/rabbitmq/erl_inetrc"
    - "erl_inetrc.j2"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart rabbitmq container

- name: Copying over definitions.json
  become: true
  vars:
    service: "{{ rabbitmq_services['rabbitmq'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ project_name }}/definitions.json"
    mode: "0660"
  with_first_found:
    - "{{ node_custom_config }}/rabbitmq/{{ inventory_hostname }}/definitions.json"
    - "{{ node_custom_config }}/rabbitmq/definitions.json"
    - "definitions.json.j2"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart rabbitmq container

- name: Copying over extra CA certificates
  become: true
  vars:
    service: "{{ rabbitmq_services['rabbitmq'] }}"
  copy:
    src: "{{ kolla_certificates_dir }}/ca/"
    dest: "{{ node_config_directory }}/{{ project_name }}/ca-certificates"
    mode: "0644"
  when:
    - rabbitmq_enable_tls | bool
    - kolla_copy_ca_into_containers | bool
    - service | service_enabled_and_mapped_to_host
  notify:
    - Restart rabbitmq container

- name: Copying over TLS certificate
  become: true
  vars:
    service: "{{ rabbitmq_services['rabbitmq'] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ project_name }}/{{ project_name }}-cert.pem"
    mode: "0644"
  with_first_found:
    - "{{ kolla_certificates_dir }}/{{ inventory_hostname }}/{{ project_name }}-cert.pem"
    - "{{ kolla_certificates_dir }}/{{ inventory_hostname }}-cert.pem"
    - "{{ kolla_certificates_dir }}/{{ project_name }}-cert.pem"
  when:
    - rabbitmq_enable_tls | bool
    - service | service_enabled_and_mapped_to_host
  notify:
    - Restart rabbitmq container

- name: Copying over TLS key
  become: true
  vars:
    service: "{{ rabbitmq_services['rabbitmq'] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ project_name }}/{{ project_name }}-key.pem"
    mode: "0600"
  with_first_found:
    - "{{ kolla_certificates_dir }}/{{ inventory_hostname }}/{{ project_name }}-key.pem"
    - "{{ kolla_certificates_dir }}/{{ inventory_hostname }}-key.pem"
    - "{{ kolla_certificates_dir }}/{{ project_name }}-key.pem"
  when:
    - rabbitmq_enable_tls | bool
    - service | service_enabled_and_mapped_to_host
  notify:
    - Restart rabbitmq container

- include_tasks: check-containers.yml
  when: kolla_action != "config"
