---
- include_tasks: register.yml
  when: inventory_hostname in groups['freezer-api']

- include_tasks: config.yml

- include_tasks: bootstrap_service.yml
  when: inventory_hostname in groups['freezer-api']

- include_tasks: clone.yml
  when: freezer_dev_mode | bool

- name: Flush handlers
  meta: flush_handlers
