---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - nova_ssh
      - nova_libvirt
  register: container_facts

- name: Checking available compute nodes in inventory
  vars:
    nova_compute_ironic: "{{ nova_services['nova-compute-ironic'] }}"
  fail:
    msg: >
      At least 1 compute node required in inventory when ironic is disabled.
  when:
    - groups[nova_cell_compute_group] | length < 1
    - not nova_compute_ironic.enabled | bool

- name: Checking free port for Nova SSH
  vars:
    nova_ssh: "{{ nova_cell_services['nova-ssh'] }}"
  wait_for:
    host: "{{ migration_interface_address }}"
    port: "{{ nova_ssh_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['nova_ssh'] is not defined
    - nova_ssh.enabled | bool
    - inventory_hostname in groups[nova_ssh.group]

- name: Checking free port for Nova Libvirt
  vars:
    nova_libvirt: "{{ nova_cell_services['nova-libvirt'] }}"
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ nova_libvirt_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['nova_libvirt'] is not defined
    - nova_libvirt.enabled | bool
    - inventory_hostname in groups[nova_libvirt.group]

- name: Checking that libvirt is not running
  vars:
    nova_libvirt: "{{ nova_cell_services['nova-libvirt'] }}"
  stat: path=/var/run/libvirt/libvirt-sock
  register: result
  failed_when: result.stat.exists
  when:
    - nova_compute_virt_type in ['kvm', 'qemu']
    - container_facts['nova_libvirt'] is not defined
    - inventory_hostname in groups[nova_libvirt.group]
