---
- name: Restart glance-api container
  vars:
    service_name: "glance-api"
    service: "{{ glance_services[service_name] }}"
  become: true
  service:
    name: "{{ service_name }}"
    state: restarted
    enabled: true
  when:
    - kolla_action != "config"

- name: Restart glance-tls-proxy container
  vars:
    service_name: "glance-tls-proxy"
    service: "{{ glance_services[service_name] }}"
  become: true
  service:
    name: "{{ service_name }}"
    state: restarted
    enabled: true
  when:
    - kolla_action != "config"
