---
- include: register.yml
  when: inventory_hostname in groups['gnocchi-api']

- include: config.yml
  when: inventory_hostname in groups['gnocchi-statsd'] or
        inventory_hostname in groups['gnocchi-api'] or
        inventory_hostname in groups['gnocchi-metricd']

- include: bootstrap.yml
  when: inventory_hostname in groups['gnocchi-api']

- name: Flush handlers
  meta: flush_handlers
