---
project_name: "elasticsearch"

elasticsearch_services:
  elasticsearch:
    container_name: elasticsearch
    group: elasticsearch
    enabled: true
    image: "{{ elasticsearch_image_full }}"
    environment:
      ES_JAVA_OPTS: "{{ es_java_opts }}"
    volumes: "{{ elasticsearch_default_volumes + elasticsearch_extra_volumes }}"
    dimensions: "{{ elasticsearch_dimensions }}"
    haproxy:
      elasticsearch:
        enabled: "{{ enable_elasticsearch }}"
        mode: "http"
        external: false
        port: "{{ elasticsearch_port }}"
        frontend_http_extra:
          - "option dontlog-normal"


####################
# Elasticsearch
####################
elasticsearch_cluster_name: "kolla_logging"
es_heap_size: "1g"
es_java_opts: "{% if es_heap_size %}-Xms{{ es_heap_size }} -Xmx{{ es_heap_size }}{%endif%}"

####################
# Docker
####################
# The elasticsearch6 image is available only for CentOS 7 and CentOS 8, and
# provides a compatible migration point to CentOS 8, which only has
# Elasticsearch 6.
elasticsearch_use_v6: "{{ ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 8 }}"
elasticsearch_install_type: "{{ kolla_install_type }}"
elasticsearch_image_name: "{{ 'elasticsearch6' if elasticsearch_use_v6 | bool else 'elasticsearch' }}"
elasticsearch_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ elasticsearch_install_type }}-{{ elasticsearch_image_name }}"
elasticsearch_tag: "{{ openstack_tag }}"
elasticsearch_image_full: "{{ elasticsearch_image }}:{{ elasticsearch_tag }}"

elasticsearch_dimensions: "{{ default_container_dimensions }}"

elasticsearch_default_volumes:
  - "{{ node_config_directory }}/elasticsearch/:{{ container_config_directory }}/"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if kolla_base_distro in ['debian', 'ubuntu'] else '' }}"
  - "{{ elasticsearch_datadir_volume }}:/var/lib/elasticsearch/data"
elasticsearch_extra_volumes: "{{ default_extra_volumes }}"
