---
spark_services:
  spark-master:
    container_name: spark_master
    group: spark-master
    enabled: true
    image: "{{ spark_image_full }}"
    environment:
      # TODO: Set in dockerfile
      SPARK_HOME: /opt/spark
      PYTHONPATH: ${SPARK_HOME}/python:${PYTHONPATH}
      PYTHONPATH: ${SPARK_HOME}/python/lib/py4j-0.10.4-src.zip:${PYTHONPATH}
      SPARK_SCALA_VERSION: "2.10"
      SPARK_LOG_DIR: /var/log/kolla/spark
      SPARK_LOCAL_DIRS: /var/lib/spark/data
    volumes:
      - "{{ node_config_directory }}/spark-master/:{{ container_config_directory }}/"
      - "/etc/localtime:/etc/localtime:ro"
      - "spark:/var/lib/spark/data"
      - "kolla_logs:/var/log/kolla/"
  spark-slave:
    container_name: spark_slave
    group: spark-slave
    enabled: true
    image: "{{ spark_image_full }}"
    environment:
      # TODO: Set in dockerfile
      SPARK_HOME: /opt/spark
      PYTHONPATH: ${SPARK_HOME}/python:${PYTHONPATH}
      PYTHONPATH: ${SPARK_HOME}/python/lib/py4j-0.10.4-src.zip:${PYTHONPATH}
      SPARK_SCALA_VERSION: "2.10"
      SPARK_LOG_DIR: /var/log/kolla/spark
      SPARK_WORKER_DIR: /var/lib/spark/data
    volumes:
      - "{{ node_config_directory }}/spark-slave/:{{ container_config_directory }}/"
      - "/etc/localtime:/etc/localtime:ro"
      - "spark:/var/lib/spark/data"
      - "kolla_logs:/var/log/kolla/"

####################
# Spark
####################
#TODO: Set JAVA_OPTS to use zookeeper for masters - see spark-env.sh in spark devstack.
spark_master_ip: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"

spark_slave_ip: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"
spark_slave_cores: 2
spark_slave_memory: 1g
# Use more sensible numbers and define in globals
spark_slave_port: 35072
spark_slave_webui_port: 8085
# TODO: Extend to multi-master
spark_masters: 'spark://{{ spark_master_ip }}:{{ spark_master_port }}'

# TODO: Template ENV VARS above, logging
#spark_log_settings: 'INFO,ROLLINGFILE'
#spark_slave_servers: "{% for host in groups['spark-slave'] %}'{{ hostvars[host]['ansible_' + hostvars[host]['api_interface']]['ipv4']['address'] }}'{% if not loop.last %},{% endif %}{% endfor %}"

####################
# Docker
####################
spark_install_type: "{{ kolla_install_type }}"
spark_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ spark_install_type }}-spark"
spark_tag: "{{ openstack_release }}"
spark_image_full: "{{ spark_image }}:{{ spark_tag }}"
