---
project_name: "mariadb"

mariadb_services:
  mariadb:
    container_name: mariadb
    group: mariadb
    enabled: true
    image: "{{ mariadb_image_full }}"
    volumes:
      - "{{ node_config_directory }}/mariadb/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "mariadb:/var/lib/mysql"
      - "kolla_logs:/var/log/kolla/"


####################
# Database
####################
database_cluster_name: "openstack"
database_max_timeout: 120

####################
# Docker
####################
mariadb_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-mariadb"
mariadb_tag: "{{ openstack_release }}"
mariadb_image_full: "{{ mariadb_image }}:{{ mariadb_tag }}"

####################
# Backups
####################
xtrabackup_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-xtrabackup"
xtrabackup_tag: "{{ openstack_release }}"
xtrabackup_image_full: "{{ xtrabackup_image }}:{{ xtrabackup_tag }}"

mariadb_backup_host: "{{ groups['mariadb'][0] }}"
mariadb_backup_database_schema: "PERCONA_SCHEMA"
mariadb_backup_database_user: "backup"
mariadb_backup_database_address: "{{ kolla_internal_fqdn }}:{{ database_port }}"
mariadb_backup_type: "full"

