---
- import_playbook: gather-facts.yml

- name: Apply role baremetal
  hosts: baremetal
  serial: '{{ kolla_serial|default("0") }}'
  gather_facts: false
  any_errors_fatal: "{{ kolla_any_errors_fatal | default(true) }}"
  roles:
    - { role: baremetal,
        tags: baremetal }
