---
- import_playbook: detect-release.yml
  vars:
    detect_release_hosts: mariadb

- name: Backup MariaDB
  hosts: mariadb
  any_errors_fatal: "{{ kolla_any_errors_fatal | default(true) }}"
  roles:
    - { role: mariadb,
        tags: mariadb,
        when: enable_xtrabackup | bool }
