---
- project:
    templates:
      - check-requirements
      - deploy-guide-jobs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-centos-source-upgrade-ceph-1
        - kolla-ansible-centos-source-upgrade-ceph-2
        - kolla-ansible-centos-source-upgrade-ceph-3
        - kolla-ansible-centos-source-upgrade-ceph-4
        - kolla-ansible-ubuntu-source-upgrade-ceph-1
        - kolla-ansible-ubuntu-source-upgrade-ceph-2
        - kolla-ansible-ubuntu-source-upgrade-ceph-3
        - kolla-ansible-ubuntu-source-upgrade-ceph-4
    gate:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
    periodic:
      jobs:
        - kolla-ansible-bifrost-centos-source
        - kolla-ansible-ubuntu-source-zun
        - kolla-ansible-centos-source-scenario-nfv
        - kolla-ansible-ubuntu-source-cinder-lvm
        - kolla-ansible-centos-source-cinder-lvm
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
        - kolla-ansible-centos-source-upgrade-ceph
        - kolla-ansible-ubuntu-source-upgrade-ceph
