---
- name: Wait for kibana port
  wait_for:
    host: "{{ kolla_internal_vip_address }}"
    port: "{{ kibana_server_port }}"
  run_once: true

- name: Register the kibana index in elasticsearch
  uri:
    url: "{{ internal_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ elasticsearch_port }}/.kibana"
    method: PUT
    body: "{{ kibana_default_index_options | to_json }}"
    body_format: json
    status_code: 200, 201, 400
  register: result
  failed_when:
    # If the index already exists, Elasticsearch will respond with a 400 error.
    - result.status == 400
    # Format: {"json": {"error": {"type": "index_already_exists_exception"}}}
    - result.get('json', {}).get('error', {}).get('type') != 'index_already_exists_exception'
  run_once: true

- name: Wait for kibana to register in elasticsearch
  uri:
    url: "{{ internal_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ elasticsearch_port }}/.kibana"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 20
  delay: 2
  run_once: true
